### ISSUE TITLE
Error exporting entry not in a folder

### ISSUE THREAD

**Issue by trdischat** [sytone/foundry-vtt-journal-sync#5]
Trying to export a journal entry that is NOT stored in a folder failed.  In the console, the module reported:

`Uploading journal-sync/test5e//First Entry (hKX2V3Lo3GUne88M).md`

It looks like it had trouble with the double slash.  When I moved the journal entry down into a folder, the export worked.

Is there a problem with line 375 of `journal-sync.js`? If I comment out this line of code, the problem seems to go away.

**Comment by sytone** [comment]
Will review. Have not seen a issue with the double slash. Is this hosted or local?

**Comment by trdischat** [comment]
Hosted on Ubuntu at Digital Ocean. As noted in my other report, the potentially extra line may be 383.

**Comment by sytone** [comment]
Please update to v0.6.12

**Comment by trdischat** [comment]
It is working now.  Thanks.
