### ISSUE TITLE
Can only export once on hosted FVTT

### ISSUE THREAD

**Issue by trdischat** [sytone/foundry-vtt-journal-sync#6]
I am running FVTT 0.6.5 on a remote Ubuntu server on Digital Ocean.  I can run the module once successfully to export all journal entries.  But it fails if I edit the entries in FVTT and try to export them again.  I get this error in the console:

`journal-sync.js:399 Uncaught (in promise) EEXIST: file already exists, mkdir '/home/taylor/foundrydata/Data/journal-sync/test5e/'`

Why is it trying to create the folders again?

Is there a problem with line 375 of `journal-sync.js`?  It seems to be trying to recreate the parent folder.  If I comment out this line of code, the problem seems to go away.

**Comment by sytone** [comment]
I'll review the code as it was catching these errors. There is no simple way to check for a folder to exist so I have to see if there is a error as the folder already exists and then handle it. 

Recent changes modified this logic and may be causing the issue.

**Comment by trdischat** [comment]
I did not spend a lot of time reviewing the code, but it looked like line 375 might be extra. Line 376 is what really tests for the existence of folders, isn’t it?

**Comment by trdischat** [comment]
My apologies, but I may have the wrong line number. Checking again, it may be line 383.  It reads:

`await FilePicker.createDirectory(markdownPathOptions.activeSource, parentPath);`

**Comment by sytone** [comment]
Yep, that is the issue. I have modified this to catch the error and continue if the folder is already there. Just tested locally and working. Will do some more validation and fix a issue with filenames I just found and push v0.6.11 which should fix it.

**Comment by sytone** [comment]
Please update to v0.6.12

**Comment by trdischat** [comment]
It is working now.  Thanks.
