### ISSUE TITLE
Using Journal Notes button to export only exported 2 out of 25 notes

### ISSUE THREAD

**Issue by FilBot3** [sytone/foundry-vtt-journal-sync#7]
When I tried running the `/js export` command, I had an error that it wasn't a command. Then I tried to use the Journal Notes Export button, and it said that it only exported two notes and it completed. So I looked at the `${HOME}/.local/share/FoundryVTT/Data/journal-sync` folder saw it only exported 2 items out of 25 and an empty folder. Is there something I did wrong?

FoundryVTT Version: 0.6.5
foundry-vtt-journal-sync version: 0.5.0 (installed through module manager)

**Comment by sytone** [comment]
There is a issue in the current release where the parent folder was being created but throwing a error on the second run. Fixing it now.

**Comment by sytone** [comment]
Please update to v0.6.12

**Comment by FilBot3** [comment]
I'll have to update using the manifest URL, not through the modules manager?

**Comment by FilBot3** [comment]
yes, I had to grab the raw URL to the module.json and use that as the path when installing the module.
